trigger:
  branches:
    include:
    - main
    - develop
    - release/*
    - feature/cicd/*
    - feature/*

  paths:
    include: 
    - alz/infrastructure
    - feature/*

stages: 
  - template: ../../templates/yaml/environments.yml
    parameters:
      buildTemplatePath:  ../../alz/infrastructure/yaml/build.yml
      deployTemplatePath: ../../alz/infrastructure/yaml/deploy.yml
      landingZone:        alz
   
